#!/bin/bash

function worked {
	if (( $1 == 0 ))
	then
		echo -n "[ OK  ]	"
	else
		echo -n "[ NOK ]	"
	fi
}

function ncCheck {
	ip="$1"
	port="$2"
	proto="$3"
	options="-z$proto -w 3"
	nc $options $ip $port >/dev/null 2>&1
	worked $?
	echo -n "$ip on port $port"
	if [[ $proto == "u" ]]
	then
		echo " UDP"
	else
		echo ""
	fi
}

function webCheck {
	site=$1
	curl --connect-timeout 3 -I "$site" 2>&1 | grep "HTTP/1.1 200 OK" >/dev/null 2>&1
	worked $?
	echo "$site"
}

function outBound {
	# Outbound Tests
	echo "Performing YUM repo check"
	for line in $urls
	do
		webCheck $line
	done

	echo "Performing DNS check"
	for line in $DNSips
	do
		ncCheck "$line" 53 
	done

	echo "Git Hub Checks"
	for line in $gitHub
	do
		ncCheck github.com $line
	done

	echo "Random Web Connections"
	for line in $outsideWorld
	do
		ncCheck $line 80
		ncCheck "$line" 443
	done

	echo "Google Mail Server Check"
	for line in $gMail
	do
		ncCheck "$line" 25
	done
}

function inBound {
	ncCheck $1 22
	ncCheck $1 53
	ncCheck $1 53 u
	ncCheck $1 80
	ncCheck $1 443
	ncCheck $1 903
	ncCheck $1 324
	ncCheck $1 194 u
	ncCheck $1 903 u
}

if [[ $1 == OUT ]]
then
	outBound
else
	inBound $1
fi

# Data

ACE2FRO="80/tcp
5672/tcp"

FRO2ACE="80/tcp"

CORE2FRO="22/tcp
68/tcp
80/tcp
161/udp
10050/tcp"

FRO2CORE="25/tcp
53/tcp
53/udp
67/tcp
67/udp
69/udp
80/tcp
123/udp
389/tcp
443/tcp
689/tcp
1514/tcp
2514/tcp
3514/tcp
5601/tcp
8080/tcp
8140/tcp
10051/tcp
61613/tcp"

FRO2PAS="80/tcp
9080/tcp"

PAS2FRO="80/tcp"

CORE2PAS="22/tcp
68/tcp
80/tcp
161/udp
10050/tcp"

PAS2CORE="25/tcp
53/tcp
53/udp
67/tcp
67/udp
69/udp
80/tcp
123/udp
389/tcp
443/tcp
689/tcp
1514/tcp
2514/tcp
3514/tcp
5601/tcp
8080/tcp
8140/tcp
10051/tcp
61613/tcp"

PAS2BRO="80/tcp
9200/tcp
9300/tcp"

CORE2BRO="22/tcp
68/tcp
80/tcp
161/udp
10050/tcp"

BRO2CORE="25/tcp
53/tcp
53/udp
67/tcp
67/udp
69/udp
80/tcp
123/udp
389/tcp
443/tcp
689/tcp
1514/tcp
2514/tcp
3514/tcp
5601/tcp
8080/tcp
8140/tcp
10051/tcp
61613/tcp"

PAS2CPSSRC="9200/tcp
9300/tcp"

BRO2CPSSRC="9200/tcp
9300/tcp"

CORE2CPSSRC="22/tcp
68/tcp
80/tcp
161/udp
10050/tcp"

CPSSRC2CORE="25/tcp
53/tcp
53/udp
67/tcp
67/udp
69/udp
80/tcp
123/udp
389/tcp
443/tcp
689/tcp
1514/tcp
2514/tcp
3514/tcp
5601/tcp
8080/tcp
8130/tcp
10051/tcp
61613/tcp"

BRO2CPSSRV="9081/tcp
9082/tcp
9083/tcp
9084/tcp
9085/tcp
9086/tcp
9087/tcp"

CORE2CPSSRV="22/tcp
68/tcp
80/tcp
161/udp
8080/tcp
10050/tcp"

CPSSRV2CORE="25/tcp
53/tcp
53/udp
67/tcp
67/udp
69/udp
80/tcp
123/udp
389/tcp
443/tcp
689/tcp
1514/tcp
2514/tcp
3514/tcp
8080/tcp
8140/tcp
10051/tcp"

CPSSRV2BRO="80/tcp
5672/tcp
5673/tcp"

BRO2CPSRMQ="5672/tcp
5673/tcp"

CORE2CPSRMQ="22/tcp
68/tcp
80/tcp
161/udp
10050/tcp"

CPSRMQ2CORE="25/tcp
53/tcp
53/udp
67/tcp
67/udp
69/udp
80/tcp
123/udp
389/tcp
443/tcp
689/tcp
1514/tcp
2514/tcp
3514/tcp
5601/tcp
8080/tcp
8140/tcp
10051/tcp
61613/tcp"

CORE2ITVSRV="1526/tcp
7777/tcp"

CORE2GITHUB="22/tcp
80/tcp
443/tcp
9418/tcp"

CORE2DNS="193.35.11.238:53/tcp
193.35.8.238:53/tcp"

CORE2EMAIL="itv.com.s200a2.psmtp.com
itv.com.s200b1.psmtp.com
itv.com.s200a1.psmtp.com
itv.com.s200b2.psmtp.com
alt1.gmr-smtp-in.l.google.com
alt2.gmr-smtp-in.l.google.com
gmr-smtp-in.l.google.com"

CORE2MGMT="25/tcp
53/tcp
53/udp
80/tcp
389/tcp
443/tcp
689/tcp
80801/tcp"

MGMT2CORE="22/tcp
53/tcp
53/udp
80/tcp
443/tcp
8443/tcp
9200/tcp
9300/tcp"

ITVSRV2CPSSRV="9082/tcp"

CPSSRV2ITVSRV="1526/tcp
7777/tcp"

GIR2CORE="22/tcp
53/tcp
53/udp
80/tcp
443/tcp"

JUNIPER2CORE="22/tcp
53/tcp
53/udp
80/tcp
443/tcp"

CITRIX2CORE="22/tcp
53/tcp
53/udp
80/tcp
443/tcp"

CORE2GIR="5555/tcp"

GIR2FRO="80/tcp
5672/tcp"

JUNIPER2FRO="80/tcp
5672/tcp"

CITRIX2FRO="80/tcp
5672/tcp"

GIR2BRO="80/tcp
5672/tcp"

JUNIPER2BRO="80/tcp
5672/tcp"

CITRIX2BRO="80/tcp
5672/tcp"
